services:
    database:
        container_name: postgres_container
        image: postgres:18
        restart: unless-stopped
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - app_network
        volumes:
            - pg_volume:/var/lib/postgresql
        healthcheck:
            test:
                - CMD-SHELL
                - >-
                    PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h localhost -U
                    ${POSTGRES_USER} -d ${POSTGRES_DB}
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 20s

    cache:
        container_name: redis_container
        image: redis:8.6.2
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: redis-server ${REDIS_ARGS}
        networks:
            - app_network
        volumes:
            - redis_volume:/data
        healthcheck:
            test:
                - CMD
                - redis-cli
                - "-a"
                - ${REDIS_PASSWORD}
                - ping
            interval: 5s
            timeout: 5s
            retries: 10
networks:
    app_network: {}
volumes:
    pg_volume: {}
    redis_volume: {}
